services:
  llmwrangler:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./prompts:/prompts
    command: ./llmwrangler -listen 7001 -warmup-prompt-file /prompts/warmup_summary.tpl -llmhost localhost:8081
    network_mode: "host"
